const PREFIX = 'Pokedex/';

export const GET_POKEMONS_REQUEST = `${PREFIX}GET_POKEMONS_REQUEST`;
export const GET_POKEMONS_SUCCESS = `${PREFIX}GET_POKEMONS_SUCCESS`;
export const GET_POKEMONS_ERROR = `${PREFIX}GET_POKEMONS_ERROR`;

export const GET_POKEMON_REQUEST = `${PREFIX}GET_POKEMON_REQUEST`;
export const GET_POKEMON_SUCCESS = `${PREFIX}GET_POKEMON_SUCCESS`;
export const GET_POKEMON_ERROR = `${PREFIX}GET_POKEMON_ERROR`;

export const GET_POKEMONS_BY_TYPE_REQUEST = `${PREFIX}GET_POKEMON_BY_TYPE_REQUEST`;
export const GET_POKEMONS_BY_TYPE_SUCCESS = `${PREFIX}GET_POKEMON_BY_TYPE_SUCCESS`;
export const GET_POKEMONS_BY_TYPE_ERROR = `${PREFIX}GET_POKEMON_BY_TYPE_ERROR`;
