const PREFIX = 'App/';

export const GET_STATS_REQUEST = `${PREFIX}GET_STATS_REQUEST`;
export const GET_STATS_SUCCESS = `${PREFIX}GET_STATS_SUCCESS`;
export const GET_STATS_ERROR = `${PREFIX}GET_STATS_ERROR`;

export const GET_TYPES_REQUEST = `${PREFIX}GET_TYPES_REQUEST`;
export const GET_TYPES_SUCCESS = `${PREFIX}GET_TYPES_SUCCESS`;
export const GET_TYPES_ERROR = `${PREFIX}GET_TYPES_ERROR`;

export const GET_DATA_REQUEST = `${PREFIX}GET_DATA_REQUEST`;
export const GET_DATA_SUCCESS = `${PREFIX}GET_DATA_SUCCESS`;
export const GET_DATA_ERROR = `${PREFIX}GET_DATA_ERROR`;
